package main

import (
	"context"
	"strings"
	"testing"

	"github.com/nbd-wtf/go-nostr"
	"github.com/nbd-wtf/go-nostr/nip19"
)

// mentionFixture wires a monitor with no relays, so any attempt to reply fails
// to publish rather than reaching the network. What is under test is whether a
// reply is attempted at all.
func mentionFixture(t *testing.T) (*MentionMonitor, *Storage) {
	t.Helper()

	storage := newTestStorage(t)
	privkey := nostr.GeneratePrivateKey()
	pubkey, _ := nostr.GetPublicKey(privkey)

	return NewMentionMonitor(pubkey, privkey, storage, NewPostFetcher(nil), nostr.NewSimplePool(context.Background())), storage
}

func mention(t *testing.T, content string) *nostr.Event {
	t.Helper()

	evt := &nostr.Event{CreatedAt: nostr.Now(), Kind: 1, Tags: nostr.Tags{}, Content: content}
	if err := evt.Sign(nostr.GeneratePrivateKey()); err != nil {
		t.Fatalf("failed to sign: %v", err)
	}
	return evt
}

// Naming the board in a note is talking about it, not to it. Answering those
// turned the account into something that interrupts people mid-conversation.
func TestMentionWithoutANoteGetsNoReply(t *testing.T) {
	monitor, storage := mentionFixture(t)

	for _, content := range []string{
		"nostr:npub1... has been good lately",
		"anyone tried holoboard?",
		"@holoboard",
		"",
	} {
		event := mention(t, content)
		if err := monitor.ProcessMention(context.Background(), event); err != nil {
			t.Errorf("%.30q produced an error instead of silence: %v", content, err)
		}
		// Marked, so it is not reconsidered on the next pass.
		if !storage.IsMentionProcessed(event.ID) {
			t.Errorf("%.30q was left unprocessed and will come round again", content)
		}
	}
}

// A public request needs an explicit command. References alone also occur in
// replies, media URLs and ordinary conversation.
func TestPromoteCommandIsWhatMakesItARequest(t *testing.T) {
	const note = "note1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
	const nevent = "nevent1qqsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
	const hex = "1111111111111111111111111111111111111111111111111111111111111111"

	silent := []string{
		"anyone tried holoboard?",
		"@holoboard",
		"nostr:npub1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq is worth a look",
		"look at " + note,
		"@holoboard I think this could promote nostr:" + note,
		"@holoboard please promote " + note,
		"@holoboard promote this project",
		"@holoboard promote https://media.example/" + hex + ".jpg",
		"https://media.example/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.jpg",
		"",
	}
	for _, content := range silent {
		if got, command := parsePromotionCommand(mention(t, content)); command || got != "" {
			t.Errorf("%.34q read as command=%t target=%q", content, command, got)
		}
	}

	requests := []string{
		"promote " + note,
		"PROMOTE nostr:" + nevent,
		"@holoboard promote " + hex + ".",
		"nostr:npub1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq promote nostr:" + note,
	}
	for _, content := range requests {
		if got, command := parsePromotionCommand(mention(t, content)); !command || got == "" {
			t.Errorf("%.34q read as command=%t target=%q", content, command, got)
		}
	}
}

func TestWebsitePromotionCommandShape(t *testing.T) {
	const noteID = "1111111111111111111111111111111111111111111111111111111111111111"
	relayKey := nostr.GeneratePrivateKey()
	relayPubkey, err := nostr.GetPublicKey(relayKey)
	if err != nil {
		t.Fatal(err)
	}
	npub, err := nip19.EncodePublicKey(relayPubkey)
	if err != nil {
		t.Fatal(err)
	}
	nevent, err := nip19.EncodeEvent(noteID, nil, "")
	if err != nil {
		t.Fatal(err)
	}

	evt := mention(t, "nostr:"+npub+" promote nostr:"+nevent)
	target, command := parsePromotionCommand(evt)
	if !command {
		t.Fatal("the command generated by the website was rejected")
	}
	if got := normalizeEventID(target); got != noteID {
		t.Errorf("website command targets %q, want %q", got, noteID)
	}
}

func TestPromotionalReplyUsesANativeQuote(t *testing.T) {
	const noteID = "2222222222222222222222222222222222222222222222222222222222222222"
	relays := []string{"wss://relay.example.com", "wss://other.example.com"}
	monitor, _ := mentionFixture(t)
	monitor.fetcher = NewPostFetcher(relays)

	authorKey := nostr.GeneratePrivateKey()
	author, err := nostr.GetPublicKey(authorKey)
	if err != nil {
		t.Fatal(err)
	}
	request := mention(t, "@holoboard promote")
	note := &nostr.Event{
		ID:      noteID,
		PubKey:  author,
		Kind:    1,
		Content: "This original content must not be copied into the reply.",
	}

	reply, err := monitor.buildPromotionalReply(request, note)
	if err != nil {
		t.Fatal(err)
	}

	if !strings.HasPrefix(reply.Content, promotionalReplyCopy+"\n\nnostr:nevent1") {
		t.Fatalf("unexpected reply content: %q", reply.Content)
	}
	if strings.Contains(reply.Content, note.Content) {
		t.Error("reply copied the original note instead of quoting it")
	}

	parts := strings.Split(reply.Content, "nostr:")
	if len(parts) != 2 {
		t.Fatalf("reply contains %d Nostr references, want one", len(parts)-1)
	}
	prefix, value, err := nip19.Decode(parts[1])
	if err != nil {
		t.Fatalf("decode quote reference: %v", err)
	}
	pointer, ok := value.(nostr.EventPointer)
	if !ok || prefix != "nevent" {
		t.Fatalf("quote decoded as %q %T, want nevent pointer", prefix, value)
	}
	if pointer.ID != noteID || pointer.Author != author {
		t.Errorf("quote points to id=%q author=%q, want id=%q author=%q", pointer.ID, pointer.Author, noteID, author)
	}
	if len(pointer.Relays) != len(relays) || pointer.Relays[0] != relays[0] || pointer.Relays[1] != relays[1] {
		t.Errorf("quote relays = %v, want %v", pointer.Relays, relays)
	}

	assertTag := func(name string, want nostr.Tag) {
		t.Helper()
		tag := reply.Tags.GetFirst([]string{name})
		if tag == nil {
			t.Fatalf("reply has no %q tag", name)
		}
		if len(*tag) != len(want) {
			t.Fatalf("%q tag = %v, want %v", name, *tag, want)
		}
		for i := range want {
			if (*tag)[i] != want[i] {
				t.Fatalf("%q tag = %v, want %v", name, *tag, want)
			}
		}
	}
	assertTag("e", nostr.Tag{"e", request.ID, "", "root"})
	assertTag("p", nostr.Tag{"p", request.PubKey})
	assertTag("q", nostr.Tag{"q", noteID, relays[0], author})
	assertTag("promoted_note", nostr.Tag{"promoted_note", noteID})
}

func TestPromotionalReplyQuoteNeedsNoRelayHint(t *testing.T) {
	const noteID = "3333333333333333333333333333333333333333333333333333333333333333"
	monitor, _ := mentionFixture(t)
	author, err := nostr.GetPublicKey(nostr.GeneratePrivateKey())
	if err != nil {
		t.Fatal(err)
	}

	reply, err := monitor.buildPromotionalReply(mention(t, "promote"), &nostr.Event{ID: noteID, PubKey: author, Kind: 1})
	if err != nil {
		t.Fatal(err)
	}

	q := reply.Tags.GetFirst([]string{"q"})
	if q == nil || len(*q) != 4 {
		t.Fatalf("q tag = %v, want id, empty relay slot and author", q)
	}
	if (*q)[1] != noteID || (*q)[2] != "" || (*q)[3] != author {
		t.Errorf("q tag = %v, want [q %s <empty> %s]", *q, noteID, author)
	}

	reference := strings.TrimPrefix(strings.Split(reply.Content, "nostr:")[1], " ")
	_, value, err := nip19.Decode(reference)
	if err != nil {
		t.Fatalf("decode quote reference: %v", err)
	}
	pointer := value.(nostr.EventPointer)
	if len(pointer.Relays) != 0 || pointer.Author != author {
		t.Errorf("quote pointer relays=%v author=%q, want no relays and author %q", pointer.Relays, pointer.Author, author)
	}
}

// A quote supplies the target only when the author explicitly asks to promote.
func TestPromoteCommandCanTargetAQuote(t *testing.T) {
	id := "1111111111111111111111111111111111111111111111111111111111111111"

	for _, test := range []struct {
		content string
		want    string
	}{
		{content: "@holoboard promote", want: id},
		{content: "nostr:npub1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq promote!", want: id},
		{content: "@holoboard should we promote this?", want: ""},
		{content: "this is worth a look", want: ""},
	} {
		evt := &nostr.Event{
			CreatedAt: nostr.Now(), Kind: 1, Content: test.content,
			Tags: nostr.Tags{nostr.Tag{"q", id}},
		}
		if err := evt.Sign(nostr.GeneratePrivateKey()); err != nil {
			t.Fatalf("failed to sign: %v", err)
		}

		if got := mentionedNote(evt); got != test.want {
			t.Errorf("mentionedNote(%q) = %q, want %q", test.content, got, test.want)
		}
	}
}

func TestReplyWithImageHashAndProfileMentionIsNotARequest(t *testing.T) {
	const hash = "a65eeb55c7389044a5eb3f638655b3d3f4bfec8a16fef52313c84c84faaa4377"
	evt := mention(t, "nostr:nprofile1qqsyexample not sure if you yourself promoted your note on holoboard but it looks much nicer now after this update https://media.example/"+hash+".jpg")
	evt.Tags = nostr.Tags{
		{"e", "cbd91bb5566fd2f701f1a90f3597ada810abb2ae58c3d2942b6ef66da5aeaf8e", "", "root"},
		{"p", testRelayPubkey},
	}

	if got := mentionedNote(evt); got != "" {
		t.Errorf("ordinary reply was read as a promotion request for %q", got)
	}

	monitor, storage := mentionFixture(t)
	if err := monitor.ProcessMention(context.Background(), evt); err != nil {
		t.Fatalf("ordinary reply produced an error instead of silence: %v", err)
	}
	if !storage.IsMentionProcessed(evt.ID) {
		t.Error("ordinary reply was not marked as processed")
	}
}
